### ISSUE TITLE
Cannot implicitly convert type 'System.Threading.Tasks.Task'<T>' to 'System.Threading.Tasks.Task<T>'

### ISSUE THREAD

**Issue by AnassL** [zHaytam/RepositoryPatternExample#1]
Hi Haytam, and congrats for the awesome article, 
For my case, I am using ASP.Net Core 3.0, and in the repository I am inheriting from class rather than BaseEntity because some of my entities have different Identifier types.

```
public class EfRepository<T> : IAsyncRepository<T> where T : class
{
    . . . 

    public Task<T> GetById(string id) => Context.Set<T>().FindAsync(id);

    . . . 
}
```
The error is:

> Cannot implicitly convert type 'System.Threading.Tasks.Task'<T>' to 'System.Threading.Tasks.Task<T>' [Persistence]csharp(CS0029)

Then when tried to use the repository in the controller:

```
    [Route("api/[controller]")]
    [ApiController]
    public class GroupsController : ControllerBase
    {
        private readonly IAsyncRepository _repository;

        . . .
```
I got the error:

> Using the generic type 'IAsyncRepository<T>' requires a type 1 argument

**Comment by zHaytam** [comment]
Hello Anass, thank you!  
For the first issue, I'm not sure if that's the full error message or something is missing (it's the same type as you can see)...  
For the second issue, in order to use the repository you'll need to specify an entity type (e.g. `IAsyncRepository<BlogPost>`, each repository only handles 1 entity.

Hope this helps!

**Comment by AnassL** [comment]
Thank you for the quick reply, the second is solved, and for the first one here is a screenshot of the error:
https://paste.pics/6fd4c47a8cf27238a83f503861c44879
Please if you would like more details about this issue, let me know

**Comment by AnassL** [comment]
Ok, the error comes from the fact that IAsyncRepository doesn't inherit from BaseClass, so no Id property is available. Now I have to find a way how to deal with this GetById method.

**Comment by zHaytam** [comment]
Actually no, they seem to have changed the signature of the method `Find`, it now returns `ValueTask<T>` instead of `Task<T>`, what version are you using?

Anyway the simple fix would be to change the signature of the `Find` method in `IAsyncRepository` and `EfRepository`.

**Comment by AnassL** [comment]
Using .Net Core 3.0

**Comment by AnassL** [comment]
Trying it like this:
        public Task<T> GetById(string id) => Context.Set<T>().FindAsync(id).AsTask();

**Comment by zHaytam** [comment]
That won't help you, change the method to `public ValueTask<T> GetById(string id) => Context.Set<T>().FindAsync(id);` in both `IAsyncRepository` and `EfRepository`.

**Comment by AnassL** [comment]
public Task GetById(string id) => Context.Set().FindAsync(id).AsTask();
Worked !!!

**Comment by AnassL** [comment]
But maybe your method is better, I need to think a bit about both, thanks to your tip I succeeded, now I have to check the how the stuff would be implemented in the API controllers...
Thanks a lot for your help Haytam.

**Comment by AnassL** [comment]
Following [this link](https://blog.marcgravell.com/2019/08/prefer-valuetask-to-task-always-and.html), your method is better, I tried it and it worked too.

EfRepository:
`public ValueTask<T> GetById(string id) => Context.Set<T>().FindAsync(id);`

IAsyncRepository
`ValueTask<T> GetById(string id);`

**Comment by zHaytam** [comment]
No problem!
